import { AnalysisReport, Screenshot } from '../types';

export interface SharedAuditData {
    id: string;
    url: string;
    report: AnalysisReport;
    screenshots: Screenshot[];
    screenshotMimeType: string;
    whiteLabelLogo?: string | null;
    createdAt: string;
    inputs?: any[];
}

// Backend URL logic
import { getBackendUrl } from './config';

const backendUrl = getBackendUrl();
/**
 * Save audit data (Unified Flow)
 * Since every audit is now a 'job' in the backend, this is mostly a pass-through
 * or used to ensure the audit exists.
 */
export async function saveSharedAudit(data: {
    url: string;
    report: AnalysisReport;
    screenshots: Screenshot[];
    screenshotMimeType: string;
    whiteLabelLogo?: string | null;
}): Promise<string> {
    console.warn('[auditStorage] saveSharedAudit called without ID. Falling back to local state (Audit IDs should ideally be pre-generated by the backend).');

    // In the new architecture, we should always have a jobId from the start.
    // If we don't, we return a temporary ID or handle it.
    return 'unsaved-' + Date.now();
}

/**
 * Retrieve shared audit data by ID from the DB
 * Returns null if not found
 */
export async function getSharedAudit(auditId: string): Promise<SharedAuditData | null> {
    // Forward to getAuditJob logic which queries API (unified)
    const job = await getAuditJob(auditId, true);
    if (!job || !job.report_data) return null;

    const report = job.report_data;
    const screenshots = report.screenshots || [];

    // Fallback if report.screenshots is empty but we have report.screenshotBase64
    if (screenshots.length === 0 && report.screenshotBase64) {
        screenshots.push({
            url: '',
            data: report.screenshotBase64,
            isMobile: false
        });
    }

    // Fix relative URL for whiteLabelLogo
    let rawLogo = job.whiteLabelLogo || report.whiteLabelLogo || null;
    let finalLogoUrl = rawLogo;
    if (finalLogoUrl && finalLogoUrl.startsWith('/uploads/')) {
        finalLogoUrl = `${backendUrl}${finalLogoUrl}`;
    }

    return {
        id: job.id,
        url: report.url || 'Unknown URL',
        report: report,
        screenshots: screenshots,
        screenshotMimeType: report.screenshotMimeType || 'image/jpeg',
        whiteLabelLogo: finalLogoUrl,
        createdAt: new Date().toISOString(),
        inputs: job.inputs || []
    };
}


export interface AuditJobData {
    id: string;
    status: 'pending' | 'processing' | 'completed' | 'failed';
    report_data?: any;
    error_message?: string;
    redirectUrl?: string; // Optional if you need to know where it would have gone
    inputs?: any[]; // AuditInput[] array
    customName?: string;
    customFavicon?: string;
    whiteLabelLogo?: string | null;
}

// Basic In-Memory Cache to prevent redundant fetches
const jobCache = new Map<string, Promise<AuditJobData | null>>();

export async function getAuditJob(jobId: string, isShared: boolean = false): Promise<AuditJobData | null> {
    // Check cache first
    const cached = jobCache.get(jobId);
    if (cached) return cached;

    const jobPromise = (async () => {
        try {
            // Prioritize API over Storage (since we stopped using Storage)
            // Try API endpoint
            const url = `${backendUrl}/api/public/jobs/${jobId}${isShared ? '?share=true' : ''}`;
            const response = await fetch(url);
            if (response.status === 403) {
                const errorData = await response.json();
                throw new Error(errorData.message || 'unclaimed');
            }

            if (response.ok) {
                const apiData = await response.json();

                // Format relative URLs from backend
                let finalWhiteLabelLogo = apiData.whiteLabelLogo;
                if (finalWhiteLabelLogo && finalWhiteLabelLogo.startsWith('/uploads/')) {
                    finalWhiteLabelLogo = `${backendUrl}${finalWhiteLabelLogo}`;
                }

                if (apiData.report_data) {
                    // Fix whitelabel logo inside report_data
                    if (apiData.report_data.whiteLabelLogo && apiData.report_data.whiteLabelLogo.startsWith('/uploads/')) {
                        apiData.report_data.whiteLabelLogo = `${backendUrl}${apiData.report_data.whiteLabelLogo}`;
                    }

                    // Fix screenshots inside report_data
                    if (Array.isArray(apiData.report_data.screenshots)) {
                        apiData.report_data.screenshots = apiData.report_data.screenshots.map((s: any) => {
                            if (s.url && s.url.startsWith('/uploads/')) {
                                return { ...s, url: `${backendUrl}${s.url}` };
                            }
                            return s;
                        });
                    }
                }

                console.log(`[AuditStorage] 🔍 Job ${jobId} fetched. Logo: ${finalWhiteLabelLogo || 'None'}`);

                return {
                    id: apiData.id,
                    status: apiData.status,
                    report_data: apiData.report_data,
                    error_message: apiData.error_message,
                    inputs: apiData.inputs,
                    customName: apiData.customName,
                    customFavicon: apiData.customFavicon,
                    whiteLabelLogo: finalWhiteLabelLogo
                };
            }

            console.warn('API fetch failed for job:', jobId);
            return null;

        } catch (error) {
            console.error('Error fetching job:', error);
            return null;
        }
    })();

    // Store in cache
    jobCache.set(jobId, jobPromise);

    // Optional: Clear cache after 30 seconds to allow for fresh data if job status changes
    setTimeout(() => { jobCache.delete(jobId); }, 30000);

    return jobPromise;
}



/**
 * Transfer audit ownership from guest/null user to logged-in user
 * Uses Backend API to bypass RLS restrictions
 */
export async function transferAuditOwnership(auditId: string, userId: string): Promise<{ success: boolean; error?: string }> {
    console.log(`[auditStorage] Request received: Transfer Audit ${auditId} -> User ${userId}`);

    try {
        const { authenticatedFetch } = await import('../lib/authenticatedFetch');

        // Use authenticatedFetch to ensure session token is sent
        const response = await authenticatedFetch(`${backendUrl}/api/v1/audit/claim`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ auditId })
        });

        const result = await response.json();

        if (!response.ok || !result.success) {
            console.error('[auditStorage] ❌ API Error transferring ownership:', result.error);
            return { success: false, error: result.error || 'Transfer failed' };
        }

        console.log(`[auditStorage] ✅ Successfully transferred audit ${auditId} to user ${userId} (via Admin API)`);
        return { success: true };

    } catch (error) {
        console.error('[auditStorage] 💥 Unexpected Error in transferAuditOwnership:', error);
        return { success: false, error: String(error) };
    }
}
